from colorama import Fore,Style,init
import os
init()

while True:
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Fore.LIGHTRED_EX+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")
    print(Style.RESET_ALL+"americaya")
    os.system("cls")